[WIP]Add automatic update func
beginerbeginer/chat-space2 pull request #25
Opened 2019-02-25 06:50 UTC by beginerbeginer

#what
自動送信機能実装
メッセージ情報入力画面に機能を追加する
メッセージを送った後に自動的にページが更新される機能を追加する。
#why
他人が送ったメッセージを自動的に更新してくれる機能が必要なため。

2019-02-25 07:22 UTC, beginerbeginer commented
[![Screenshot from Gyazo](https://gyazo.com/99be687dfa514b23174faa32aa48ff62/raw)](https://gyazo.com/99be687dfa514b23174faa32aa48ff62)

2019-02-25 07:22 UTC, beginerbeginer commented
[![Screenshot from Gyazo](https://gyazo.com/46f02952b321c5cb3fda2a0f600bffd1/raw)](https://gyazo.com/46f02952b321c5cb3fda2a0f600bffd1)

2019-02-25 07:24 UTC, beginerbeginer commented
5秒でページが更新される機能を実装した。
console:log　を使い
実際に検証ページで5sごとに値が増えていくのを確認できた。

2019-02-25 07:28 UTC, ghost requested changes

2019-02-25 07:28 UTC, hiroki5123 commented on app/assets/javascripts/message.js
> +      $('#new_message')[0].reset();
これでは、メッセージの数だけスクロールされてメッセージの数だけフォームがリセットされるので修正しましょう。

2019-02-25 07:28 UTC, hiroki5123 commented on app/assets/javascripts/message.js
> +      var html = buildHTML(message);
eachの中はインデント深くしてください。

2019-02-25 08:27 UTC, beginerbeginer commented on app/assets/javascripts/message.js
> +      $('#new_message')[0].reset();
コメントありがとうございます。
私の基礎的な知識の不足が原因で質問の意図がつかめませんでした。
画面共有でメンターの方にも伺ったのですがわからず...

自動更新の機能を考える上でのポイントや考え方をおしえていただけないでしょうか？

2019-02-25 08:27 UTC, beginerbeginer commented on app/assets/javascripts/message.js
> +      var html = buildHTML(message);
修正しました。確認よろしくお願い致します。

2019-02-25 08:29 UTC, beginerbeginer commented
・原因
単純に基礎知識、経験の不足
自動更新についての考え方、押さえるべきポイントがわかっていない。
・解決に向けて
メンターにも聞いたが解決策はでず、ネットで調べたが情報はあまり見つかりませんでした。

2019-02-25 08:44 UTC, hiroki5123 commented on app/assets/javascripts/message.js
> +      $('#new_message')[0].reset();
もし、自動更新で取ってきたメッセージが5つある場合、
each文で処理をしているので、その中に書いていある
```
var html = buildHTML(message);
      $('.messages').append(html);
      $('.chat-main__body').animate({ scrollTop: $(".messages")[0].scrollHeight }, 'fast');
      $('#new_message')[0].reset();
```
の処理が5回行われます。
そうなると、animateやreset()も必要がないのに5回実行されますので、eachで処理をした後に1回実行すればいいものはeachの外に出しましょう

という旨のコメントでした。

2019-02-25 08:45 UTC, hiroki5123 commented on app/assets/javascripts/message.js
> +      $('#new_message')[0].reset();
もしわからなければ再度ご質問ください。

2019-02-25 08:47 UTC, beginerbeginer commented on app/assets/javascripts/message.js
> +      $('#new_message')[0].reset();
ありがとうございます。

2019-02-25 08:51 UTC, ghost requested changes

2019-02-25 08:51 UTC, hiroki5123 commented on app/controllers/messages_controller.rb
> +      format.json { @new_messages = Message.where('id > ?', params[:id])}
これでは他のグループに投稿されたメッセージもappendされませんか・・・？

2019-02-25 08:51 UTC, hiroki5123 commented on app/assets/javascripts/message.js
> +        dataType: 'json'
パラメーター含めてないですが、きちんとコントローラーでid取得できているのでしょうか・・・？

2019-02-26 05:21 UTC, beginerbeginer commented on app/controllers/messages_controller.rb
> +      format.json { @new_messages = Message.where('id > ?', params[:id])}
すいません。どこを修正箇所と意図を把握できずどこを修正すればいいのでしょうか？

html形式でアクセスがあった場合は特に何もなし(@messages = Message.allして終わり）
json形式でアクセスがあった場合は、params[:message][:id]よりも大きいidがないかMessageから検索して、@new_messageに代入する
という意図で書きました。

2019-02-26 05:23 UTC, beginerbeginer commented on app/assets/javascripts/message.js
> +        dataType: 'json'
修正しました。確認よろしくお願い致します。

2019-02-26 07:14 UTC, beginerbeginer commented
[![Screenshot from Gyazo](https://gyazo.com/20857fe0a154fdd00fc11e72f76ea6c4/raw)](https://gyazo.com/20857fe0a154fdd00fc11e72f76ea6c4)

画面の自動更新機能の実装をしました。
message.jsのセレクタを修正しました。
→送信ボタンが複数回押しても機能する
index.json.builder の記述を修正しました。
→メッセージ送信後、名前の表示が正しくされるようにしました。

2019-02-26 07:16 UTC, ghost approved these changes
LGTMです！

2019-02-26 07:17 UTC, merged