[wip]フロントビュー実装のテスト
beginerbeginer/chat-space2 pull request #3
Opened 2019-02-11 11:23 UTC by beginerbeginer

#what
フロントビューの実装
#why
フロントビューの確認をしてもらうため

2019-02-11 11:25 UTC, beginerbeginer commented
フロントビューのコード
反映させるまでは書きました。
中途半端ですみません

2019-02-11 11:29 UTC, yuki-uchida commented
Gyazoなどで実際に作っていただいたビューのデザインが崩れていないかを見せていただきたいです！

2019-02-11 11:30 UTC, yuki-uchida requested changes

2019-02-11 11:30 UTC, yuki-uchida commented on app/assets/stylesheets/messages.scss
> +  // .header_icons {
コメントアウトは消しましょう

2019-02-11 11:30 UTC, yuki-uchida commented on app/assets/stylesheets/messages.scss
> +  .group_name {
全体的に、https://qiita.com/Takuan_Oishii/items/0f0d2c5dc33a9b2d9cb1 に沿ってクラスの命名を修正しましょう

2019-02-11 11:30 UTC, yuki-uchida commented on app/assets/stylesheets/messages.scss
> +      background: #FFFFFF;
色は変数化しておきましょう。色管理用のscssを作成しておくことによってサイト全体の色統一、変更が容易になり可読性も上がります

2019-02-12 05:05 UTC, beginerbeginer commented
![Uploading c53d185b0b633b7da019430ee3eb4604.png…]()

2019-02-12 05:06 UTC, beginerbeginer commented
https://gyazo.com/c53d185b0b633b7da019430ee3eb4604

2019-02-12 05:16 UTC, yusukeyamane commented
見せて頂いたスクリーンショットだとかなり見本と差異があるように見受けられます！
完成した後改めてPRを出して頂いても良いでしょうか？？

2019-02-12 08:53 UTC, beginerbeginer commented
[![Screenshot from Gyazo](https://gyazo.com/727861577d6520217e447aa7b4473eb0/raw)](https://gyazo.com/727861577d6520217e447aa7b4473eb0)

2019-02-12 08:58 UTC, beginerbeginer commented
cssの調整わからない
コメントアウトは消しました。

2019-02-12 09:04 UTC, yusukeyamane commented
・カリキュラムのhtml, css部分を見直していただくこと
・http://ysd-lab.jp/markup/learn.html こういった実践形式のサイトを取り組んで見ること
・残りわからない部分はhttp://www.htmq.com/csskihon/001.shtml から該当箇所を検索して実装していく

という方針になるかと思います！もしもっと具体的に方針を決めたいということであれば担当のライフコーチにご相談ください！（彼らの方がより細かいサポートができると思います！）

2019-02-12 09:44 UTC, yusukeyamane commented on app/assets/stylesheets/_color_variable.scss
> +
whiteと#fffとFFFFFFは一緒の色なので一つの変数でいいですね。
他にも同じ意味のものは同じ変数でいいです！

2019-02-12 09:55 UTC, beginerbeginer commented on app/assets/stylesheets/_color_variable.scss
> +
ありがとうございます。
アドバイスあると助かります。

2019-02-12 09:59 UTC, beginerbeginer commented
![2019-02-12 18 42 29](https://user-images.githubusercontent.com/43893159/52627219-3f489800-2ef8-11e9-8e0d-3a1889943772.png)

2019-02-12 10:00 UTC, beginerbeginer commented
https://i.gyazo.com/58e094798ab5ab795e52e52051b6e49e.png

2019-02-12 10:04 UTC, beginerbeginer commented
![2019-02-12 18 42 29](https://user-images.githubusercontent.com/43893159/52627410-a1090200-2ef8-11e9-8dcd-ac245ad6187b.png)

習字みたいに何度か繰り返すしかないと思いました。
目コピで作成は自分ではまだ厳しい。
要素をどう分解するべきかの練習が足りない。
わかることと理解の差が大きいことを理解した。
何度か繰り返す必要があるため今回はほぼ真似て作った

2019-02-12 10:05 UTC, beginerbeginer commented
![2019-02-12 19 04 44](https://user-images.githubusercontent.com/43893159/52627587-1674d280-2ef9-11e9-8e8c-1b7b6b2e84a7.png)

2019-02-12 11:31 UTC, beginerbeginer commented
本番環境のCSSをコンソールで調べて
EBM に従って書き換える方法は現実的でしょうか？

2019-02-12 11:42 UTC, ReoKuriyama commented
経験が少ない内は真似た方が近道になると思います。
`div`を使ってどうページを分けていくかなどは実際の使われ方をみないと難しいところがあるので。
ただし、コードを写すときは何を意味しているかを把握しながらにしましょう

2019-02-12 11:45 UTC, ReoKuriyama requested changes

2019-02-12 11:45 UTC, ReoKuriyama commented on app/views/messages/index.html.haml
> +          %form#new_message.new_message{"accept-charset" => "UTF-8", :action => "/groups/149/messages", :enctype => "multipart/form-data", :method => "post"}
以下三行は手動で書くものではないです
これらはform_tag等で生成されるものです。
写すのは最悪良いですが何を意味しているか分からないまま書いても身になりません

2019-02-13 09:10 UTC, beginerbeginer commented
![2019-02-13 18 02 36](https://user-images.githubusercontent.com/43893159/52699767-dde8fd80-2fb9-11e9-90b0-2a775564c614.png)

cssの機能ごとに分けて書くとわかりやすくなることに気づけた。
htmlは場所→そこにあるクラスについて書くと場所が視覚的にイメージしやすいことに気づけた。
グループの場所は部分テンプレートが使える。
wrapperを使った理由がまだわからない。

2019-02-13 09:15 UTC, TOMARUMARU commented on app/views/layouts/mailer.html.haml
>  !!!
mailerファイルは使用しないので消してしまいましょう

2019-02-13 09:15 UTC, TOMARUMARU commented on app/views/messages/index.html.haml
> +
改行が空きすぎですね。
改行やインデントもきちんと揃えましょう

2019-02-13 09:31 UTC, beginerbeginer commented on app/views/messages/index.html.haml
> +
修正しました。確認よろしくお願い致します。

2019-02-13 09:31 UTC, beginerbeginer commented on app/views/layouts/mailer.html.haml
>  !!!
修正しました。確認よろしくお願い致します。

2019-02-13 09:45 UTC, beginerbeginer commented
修正しました。確認よろしくお願い致します。

2019-02-13 09:48 UTC, TOMARUMARU approved these changes
LGTMです！

2019-02-13 09:58 UTC, merged