[WIP]add_devise_function
beginerbeginer/chat-space2 pull request #4
Opened 2019-02-15 13:03 UTC by beginerbeginer

#what
add_devise_function

#why
ユーザ機能追加のため

2019-02-15 13:05 UTC, beginerbeginer commented
確認よろしくお願い致します。

2019-02-16 02:04 UTC, yuki-uchida requested changes

2019-02-16 02:04 UTC, yuki-uchida commented on app/assets/stylesheets/user.scss
> +  .account-page__inner {
こちら、BEMに沿ってクラス命名していただいているので、アンパサンドを活用して省略形で書きましょう 全体的に修正お願いします
参考
thttps://qiita.com/Takuan_Oishii/items/0f0d2c5dc33a9b2d9cb1

2019-02-16 08:11 UTC, beginerbeginer commented on app/assets/stylesheets/user.scss
> +  .account-page__inner {
ありがとうございます。
参考にさせていただきます。

2019-02-16 08:46 UTC, beginerbeginer commented on app/assets/stylesheets/user.scss
> +  .account-page__inner {
&__inner 
という書き方で書けばいいのでしょうか？

2019-02-16 08:49 UTC, yuki-uchida commented on app/assets/stylesheets/user.scss
> +  .account-page__inner {
そうですね、その書き方になります。

2019-02-16 08:57 UTC, beginerbeginer commented
修正しました。確認よろしくお願い致します。

2019-02-16 09:00 UTC, yuki-uchida requested changes

2019-02-16 09:00 UTC, yuki-uchida commented on app/assets/stylesheets/user.scss
> +    .field_with_errors {
この辺り、BEM にそってクラス名を書き直しましょう
参考
https://qiita.com/Takuan_Oishii/items/0f0d2c5dc33a9b2d9cb1

2019-02-16 09:00 UTC, yuki-uchida commented on app/assets/stylesheets/user.scss
> +    .account-page__inner--left{
この辺りもです

2019-02-16 09:01 UTC, beginerbeginer commented on app/assets/stylesheets/user.scss
> +    .field_with_errors {
ありがとうございます確認します

2019-02-16 09:01 UTC, beginerbeginer commented on app/assets/stylesheets/user.scss
> +    .account-page__inner--left{
見落としていました。
ありがとうございます、確認します。

2019-02-16 09:22 UTC, beginerbeginer commented on app/assets/stylesheets/user.scss
> +  .account-page__inner {
.account-page__inner--left を
&__inner--left
と書き換えるとページのビューが変わってしまいました。
この以外に書き直す方法はありますか？
そもそも書き直せないのでようか？

2019-02-16 09:32 UTC, beginerbeginer commented
修正しました。確認よろしくお願い致します。

2019-02-16 09:33 UTC, yuki-uchida requested changes

2019-02-16 09:33 UTC, yuki-uchida commented on app/assets/stylesheets/user.scss
> +    .field-label {
指摘した部分だけではなく、CSS全体的にBEMに沿って書いてください

2019-02-16 09:45 UTC, beginerbeginer commented on app/assets/stylesheets/user.scss
> +    .field-label {
かしこまりました。
質問があります。
.account-page__inner--left を
&__inner--left
と書き換えるとページのビューが変わってしまいました。
この以外に書き直す方法はありますか？
そもそも書き直せないのでようか？

2019-02-16 10:08 UTC, beginerbeginer commented on app/assets/stylesheets/user.scss
> +    .field-label {
.account-pageクラスのなかに
.header クラス
.btn クラス
がある場合はどう分ければ良いのでしょうか？
```
  &__header {
    h2 {
      margin-bottom: 10px;
      letter-spacing: 3px;
      font-size: 40px;
      font-weight: 200;

      &:after {
        content: '';
        display: block;
        width: 60px;
        margin-top: 5px;
        border-bottom: 1px solid #38aef0;
      }
    }

    h5 {
      margin-bottom: 20px;
      font-size: 14px;
      font-weight: 200;
    }

    .btn {
      margin-top: 20px;
      color: #fff;
      background-color: #ccc;
      font-size: 14px;
    }
  }
```

2019-02-16 10:13 UTC, yuki-uchida commented on app/assets/stylesheets/user.scss
> +    .field-label {
.account-pageクラスのなかに
.header クラス
.btn クラス
がある場合には、まずクラス名をaccount-page__headerなどと書き換える必要があります。
そもそもBEMというクラス命名方法に沿っていないとアンバサンドを活用した省略形も記述できないためです。

なので、まずはBEM に沿ったクラス命名をお願い致します。
また、質問がある場合にはコネクトの方がスムーズに解決できるので、そちらの使用も検討お願い致します

2019-02-16 11:00 UTC, beginerbeginer commented on app/assets/stylesheets/user.scss
> +    .field-label {
修正しました。確認よろしくお願い致します。
CSSがかからなくなってしまいました。
1度命名の仕方を見ていただけないでしょうか？
__element__element にはならないよう注意しました。

よろしくお願い申し上げます。
![fireshot capture 9 - chatspace - http___localhost_3000_users_sign_in](https://user-images.githubusercontent.com/43893159/52898791-8d75d800-3225-11e9-9724-92dd1adffede.png)

2019-02-16 11:04 UTC, TOMARUMARU commented on app/assets/stylesheets/user.scss
> +    .field-label {
修正しましたらcommitしてpushしてください

2019-02-16 12:14 UTC, beginerbeginer commented
修正しました。確認よろしくお願い致します。
```
  .field {
    margin-bottom: 10px;

    .field-label {
      padding: 10px 0;
      letter-spacing: 1px;
      font-size: 14px;
      font-weight: 200;

      i {
        font-size: 11px;
      }
    }

    .field-input {
      input {
        width: 100%;
        padding: 10px;
        letter-spacing: 1px;
      }
    }
  }

  .btn {
    display: inline-block;
    height: 50px;
    padding: 0 30px;
    line-height: 50px;
    letter-spacing: 1px;
    text-align: center;
    border: none;
    border-radius: 2px;
  }
```
どうしてもこの場所をBEMで書くことができませんでした
＠expend　や　分割する方法などやり方があれば教えていただけないでしょうか？よろしくお願い致します。

2019-02-16 12:17 UTC, TOMARUMARU commented
field-labelというclass名をflied__labelにして
```
.field {
  &__label {
　　~~~~
  }
}
```
のようにしてもダメということでしょうか？

2019-02-16 12:22 UTC, beginerbeginer commented
その変更をしてしまうとCSSが反映されなくなりました。

2019-02-16 13:01 UTC, yuki-uchida commented
こちら一度コネクトでご相談いただけますでしょうか。
正直なところ、操作しながらなぜCSSが当たらないのかを確認しながらでないと、github上でピンポイントで問題を指摘することが難しいです。

大変お手数ですが、スムーズな解決をするため、よろしくお願い致します

2019-02-17 05:43 UTC, beginerbeginer commented
![2019-02-17 14 05 41](https://user-images.githubusercontent.com/43893159/52908648-2f94cf00-32bd-11e9-8074-3120c1ae59fa.png)

account-page__inner--right クラス内にあるため
.field→.account-page__inner--right__field　
としました。

2019-02-17 05:49 UTC, beginerbeginer commented
![2019-02-17 14 46 29](https://user-images.githubusercontent.com/43893159/52908951-e9426e80-32c2-11e9-84d4-4b1080c01d8b.png)

field クラスに＆__ を書き加えようと思いましたが
CSSが外れてしまい断念

html.haml　ファイル
のクラス名を書き換えました。

2019-02-17 05:55 UTC, yuki-uchida approved these changes
かしこまりました、LGTMです！！お疲れ様でした

2019-02-17 08:24 UTC, yuki-uchida requested changes

2019-02-17 08:24 UTC, yuki-uchida commented on app/assets/stylesheets/modules/user.scss
> +      padding: 10px 0;
こちらアンバサンドを用いて省略形で書きましょう

2019-02-17 08:31 UTC, beginerbeginer commented on app/assets/stylesheets/modules/user.scss
> +      padding: 10px 0;
修正しました。確認よろしくお願い致します。

2019-02-17 08:35 UTC, yuki-uchida commented
すいません、変更が確認できなかったため、プッシュ忘れをご確認ください

2019-02-17 08:36 UTC, beginerbeginer commented
失礼しました。pushしました。

2019-02-17 08:46 UTC, beginerbeginer commented
・修正箇所
.field-label
→
&__field
・その他
サインアップ時に必要なnameカラムをストロングパラメータに
追加するメソッドを追加しました。

確認よろしくお願い申し上げます。

2019-02-17 08:47 UTC, ghost requested changes

2019-02-17 08:47 UTC, hiroki5123 commented on app/views/devise/unlocks/new.html.erb
> +<h2>Resend unlock instructions</h2>
このファイルは必要ないので削除しましょう

2019-02-17 08:47 UTC, hiroki5123 commented on app/views/devise/registrations/edit.html.erb
> +<h2>Edit <%= resource_name.to_s.humanize %></h2>
このファイルも使用しないので削除しましょう

2019-02-17 08:47 UTC, hiroki5123 commented on app/views/devise/mailer/confirmation_instructions.html.erb
> +<p>Welcome <%= @email %>!</p>
このファイルも使用しないので削除しましょう

2019-02-17 08:50 UTC, TOMARUMARU commented
修正したらpushをお願いします

2019-02-17 08:55 UTC, beginerbeginer commented on app/views/devise/mailer/confirmation_instructions.html.erb
> +<p>Welcome <%= @email %>!</p>
修正しました。確認よろしくお願い致します。

2019-02-17 08:55 UTC, beginerbeginer commented on app/views/devise/registrations/edit.html.erb
> +<h2>Edit <%= resource_name.to_s.humanize %></h2>
修正しました。確認よろしくお願い致します。

2019-02-17 08:55 UTC, beginerbeginer commented on app/views/devise/unlocks/new.html.erb
> +<h2>Resend unlock instructions</h2>
修正しました。確認よろしくお願い致します。

2019-02-17 09:02 UTC, yuki-uchida commented
LGTMです。お疲れ様でした

2019-02-17 10:03 UTC, beginerbeginer commented
application_controller.rb内に
protected は追加した方がいいのでしょうか？

2019-02-17 10:17 UTC, merged

2019-02-17 10:17 UTC, yuki-uchida reviewed
そうですね、あった方が良いでしょう。見落としていました。
他クラスからは参照する必要がない(出来ると脆弱性になる可能性がある)ためですね

2019-02-17 10:18 UTC, beginerbeginer commented
ありがとうございます。