[WIP]User edit function(ユーザの編集機能の実装
)
beginerbeginer/chat-space2 pull request #5
Opened 2019-02-17 12:34 UTC by beginerbeginer

#what
ユーザの編集機能の実装
#why
ユーザの編集機能の実装のため

2019-02-17 12:47 UTC, beginerbeginer commented
確認よろしくお願いいたします

2019-02-17 12:48 UTC, yuki-uchida requested changes

2019-02-17 12:48 UTC, yuki-uchida commented on app/views/users/edit.html.haml
> +      %a.btn{:href => "https://chat-space-sample.herokuapp.com/"} トップページに戻る
aタグは使わずlink_toで記述しましょう！

2019-02-17 12:48 UTC, yuki-uchida commented on app/views/users/edit.html.haml
> +      %form#edit_user_41.edit_user{"accept-charset" => "UTF-8", :action => "/users/41", :method => "post"}
form_forを使って記述しましょう！

2019-02-17 12:59 UTC, beginerbeginer commented
課題点
form_for
a→link_to
での書き方の訓練が足りないことがわかった。
書けるようになれれば可読性も上がる

2019-02-17 13:00 UTC, yuki-uchida commented
指摘に対しては、一つ一つリプライする形で対応を記述してください

2019-02-17 13:01 UTC, yuki-uchida approved these changes
LGTMです。お疲れ様でした

2019-02-17 13:06 UTC, beginerbeginer commented
失礼しました。気をつけます。
確認ありがとうございます。

2019-02-18 04:54 UTC, merged

2019-02-18 04:55 UTC, beginerbeginer commented
User edit function(ユーザの編集機能の実装) #5
終了